export default async function Techs(req, res) {
    res.json([
        [ "JavaScript", "javascript.svg", "https://developer.mozilla.org/docs/Web/JavaScript" ],
        [ "TypeScript", "typescript.png", "https://www.typescriptlang.org/" ],
        [ "React", "react.svg", "https://react.dev/" ],
        [ "Vue", "vue.png", "https://vuejs.org/" ],
        [ "Next.js", "next.svg", "https://nextjs.org/" ],
        [ "Nuxt.js", "nuxt.svg", "https://nuxt.com/" ],
        [ "Alpine.js", "alpine.svg", "https://alpinejs.dev/" ],
        [ "Bootstrap", "bootstrap.svg", "https://getbootstrap.com/" ],
        [ "Bulma", "bulma.svg", "https://bulma.io/" ],
        [ "CSS", "css.svg", "https://developer.mozilla.org/docs/Web/CSS" ],
        [ "HTML", "html.svg", "https://developer.mozilla.org/docs/Web/HTML" ],
        [ "Electron.js", "electron.svg", "https://www.electronjs.org/" ],
        [ "Express.js", "express.svg", "https://expressjs.com/" ],
        [ "Font Awesome", "fontawesome.png", "https://fontawesome.com/" ],
        [ "Framer Motion", "framer.svg", "https://www.framer.com/motion/" ],
        [ "Git", "git.svg", "https://git-scm.com/" ],
        [ "GitHub", "github.svg", "https://github.com/" ],
        [ "HeadlessUI", "headless.png", "https://headlessui.com/" ],
        [ "IconScout", "iconscout.png", "https://iconscout.com/" ],
        [ "MongoDB", "mongo.svg", "https://www.mongodb.com/" ],
        [ "MySQL", "mysql.png", "https://www.mysql.com/" ],
        [ "Node.js", "node.svg", "https://nodejs.org/" ],
        [ "PHP", "php.svg", "https://www.php.net/" ],
        [ "Sass", "sass.svg", "https://sass-lang.com/" ],
        [ "TailwindCSS", "tailwind.svg", "https://tailwindcss.com/" ],
        [ "Vercel", "vercel.svg", "https://vercel.com/" ],
        [ "Webpack", "webpack.svg", "https://webpack.js.org/" ],
        [ "Yarn", "yarn.svg", "https://yarnpkg.com/" ],
    ]);
};
